# Test MakeAppx and SignTool

name: FindMakeAppxSignTool

on:
  push:
    branches: [ experiments/test-makeappx-signtool ]
  pull_request:
    branches: [ experiments/test-makeappx-signtool ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  bundle:
    runs-on: windows-latest

    steps:
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
      
      - name: MakeAppx
        run: MakeAppx
