# Test MakeAppx and SignTool

name: FindMakeAppxSignTool

on:
  push:
    branches: [ experiments/test-makeappx-signtool ]
  pull_request:
    branches: [ experiments/test-makeappx-signtool ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  bundle:
    runs-on: windows-latest

    steps:
      - name: Setup Visual Studio Developer Command Prompt
        run: |
          $installationPath = vswhere.exe -latest -property installationPath
          if ($installationPath -and (test-path "$installationPath\Common7\Tools\vsdevcmd.bat")) {
            & "${env:COMSPEC}" /s /c "`"$installationPath\Common7\Tools\vsdevcmd.bat`" -no_logo && set" | foreach-object {
              $name, $value = $_ -split '=', 2
              set-content env:\"$name" $value
            }
          }
      
      - name: MakeAppx
        run: MakeAppx
